import React from "react";
import "../styles/global.css";
import { Roboto } from "next/font/google";
import Footer from "@/components/footer/footer";
const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "MAIN PAGE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={roboto.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
