import SecondaryHeader from "@/components/secondaryHeader/secondaryHeader";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "REVIEWS PAGE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <SecondaryHeader />
      {children}
    </>
  );
}
